keys:
  - &agentkey ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7k3rLnk4RTB4nF+uWPgVeDVNVfYVejVDe+e65SxdZ2 # cat ~/.ssh/id_ed25519_agent.pub
  - &agentkey2 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICGyTT466f4qYEXQx4pC7slvrknHSaoP/ZfF3IFTtH2R
creation_rules:
  - path_regex: \.credentials\.json
    key_groups:
      - age:
        - *agentkey
  - path_regex: secrets\.yaml
    key_groups:
      - age:
        - *agentkey
  - path_regex: secrets2\.yaml
    key_groups:
      - age:
        - *agentkey2
